---
name: AMD64_DARWIN

on:
  workflow_call:
    inputs:
      os:
        default: macos-latest
        required: false
        type: string
      release:
        default: https://github.com/coder5506/cm3/releases/download/bootstrap-devel
        required: false
        type: string
      bootstrap:
        default: cm3-boot-AMD64_LINUX-d5.11.3.tar.xz
        required: false
        type: string

jobs:
  build-and-test:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 45

    strategy:
      fail-fast: false
      matrix:
        backend: [c, gcc]

    env:
      CM3_TARGET: AMD64_DARWIN

    steps:
    - name: Install prerequisites
      run: |
        brew update
        brew install libxaw libxft ninja xquartz

    - name: Define install location
      run: |
        echo CM3_INSTALL="$(pwd)/../install" >> $GITHUB_ENV

    - name: Install bootstrap release
      run: |
        mkdir ../bootstrap ../build
        curl --location --silent "${{ inputs.release }}/${{ inputs.bootstrap }}" | tar Jxf - --directory=../bootstrap --strip-components=1
        cmake -S ../bootstrap -B ../build -G Ninja -DCMAKE_INSTALL_PREFIX="${CM3_INSTALL}"
        cmake --build ../build
        cmake --install ../build
        echo "${CM3_INSTALL}/bin" >> $GITHUB_PATH

    - name: Fetch sources
      uses: actions/checkout@v2

    - name: Build all the things
      run: |
        scripts/concierge.py full-upgrade --backend "${{ matrix.backend }}"

    - name: Run compiler validation suite
      continue-on-error: true
      run: |
        cm3 -DHTML
      working-directory: m3-sys/m3tests

    - name: Generate test report
      uses: dorny/test-reporter@v1
      with:
        name: ${{ format('m3tests ({0}, {1})', env.CM3_TARGET, matrix.backend) }}
        fail-on-error: false
        max-annotations: 49
        path: m3-sys/m3tests/m3tests-results.xml
        reporter: java-junit
